# Generated by Django 5.0.6 on 2024-06-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
